name: Vue Component Package
on:
  [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Run Unit Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:unit
      - name: Conventional Changelog Action
        uses: cdotyone/conventional-changelog-action@v3.8.2
        with:
          github-token: ${{ github.token }}
          tag-prefix: 'v'
          release-count: '20'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
